"""
Train a Siamese model on tube_ref / tube_test pairs.

Expected input:
    data/processed/siamese_pairs/metadata.csv
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any

import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.inference.siamese_anomaly import SiameseConfig, TubePairSiamese


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train siamese anomaly classifier on tube pairs.")
    parser.add_argument(
        "--metadata",
        type=Path,
        default=PROJECT_ROOT / "data" / "processed" / "siamese_pairs" / "metadata.csv",
        help="Metadata CSV generated by build_siamese_pairs_from_videos.py",
    )
    parser.add_argument(
        "--data-root",
        type=Path,
        default=PROJECT_ROOT / "data" / "processed" / "siamese_pairs",
        help="Root directory containing pair images",
    )
    parser.add_argument("--epochs", type=int, default=20, help="Number of training epochs")
    parser.add_argument("--batch-size", type=int, default=32, help="Batch size")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="Weight decay")
    parser.add_argument("--embedding-dim", type=int, default=128, help="Embedding dimension")
    parser.add_argument("--input-size", type=int, default=128, help="Input crop size")
    parser.add_argument("--num-workers", type=int, default=0, help="Data loader workers")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument(
        "--balanced-sampler",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Use weighted sampling so anomaly pairs appear more often in training batches.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "src" / "models" / "best_siamese.pt",
        help="Output checkpoint path",
    )
    return parser.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def get_device() -> str:
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


class SiamesePairsDataset(Dataset):
    def __init__(self, rows: list[dict[str, Any]], data_root: Path, augment: bool = False) -> None:
        self.rows = rows
        self.data_root = data_root
        self.augment = augment

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        row = self.rows[index]
        ref = self._load_image(self.data_root / row["ref_path"])
        test = self._load_image(self.data_root / row["test_path"])
        label = torch.tensor(float(row["label"]), dtype=torch.float32)
        return ref, test, label

    def _load_image(self, path: Path) -> torch.Tensor:
        image = cv2.imread(str(path), cv2.IMREAD_COLOR)
        if image is None:
            raise FileNotFoundError(f"Unable to read image: {path}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        if self.augment and random.random() < 0.5:
            image = np.ascontiguousarray(np.fliplr(image))
        tensor = torch.from_numpy(image.transpose(2, 0, 1)).float() / 255.0
        return tensor


def read_rows(metadata_path: Path) -> list[dict[str, Any]]:
    with metadata_path.open("r", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def split_rows(rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    train_rows = [row for row in rows if row.get("split") == "train"]
    val_rows = [row for row in rows if row.get("split") == "val"]
    if not train_rows or not val_rows:
        raise ValueError("Metadata must contain both train and val rows.")
    return train_rows, val_rows


def build_weighted_sampler(rows: list[dict[str, Any]], seed: int) -> WeightedRandomSampler:
    class_counts: dict[int, int] = {}
    for row in rows:
        label = int(row["label"])
        class_counts[label] = class_counts.get(label, 0) + 1

    sample_weights = [
        1.0 / max(class_counts.get(int(row["label"]), 1), 1)
        for row in rows
    ]
    generator = torch.Generator()
    generator.manual_seed(seed)
    return WeightedRandomSampler(
        weights=torch.tensor(sample_weights, dtype=torch.double),
        num_samples=len(rows),
        replacement=True,
        generator=generator,
    )


def find_best_threshold(probabilities: list[float], labels: list[int]) -> tuple[float, float]:
    best_threshold = 0.5
    best_f1 = -1.0
    for threshold in np.linspace(0.1, 0.9, 81):
        predictions = [1 if prob >= threshold else 0 for prob in probabilities]
        tp = sum(1 for pred, label in zip(predictions, labels) if pred == 1 and label == 1)
        fp = sum(1 for pred, label in zip(predictions, labels) if pred == 1 and label == 0)
        fn = sum(1 for pred, label in zip(predictions, labels) if pred == 0 and label == 1)
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = 0.0 if precision + recall == 0 else 2 * precision * recall / (precision + recall)
        if f1 > best_f1:
            best_f1 = f1
            best_threshold = float(threshold)
    return best_threshold, best_f1


def run_epoch(
    model: TubePairSiamese,
    loader: DataLoader,
    device: str,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer | None = None,
) -> dict[str, float]:
    training = optimizer is not None
    model.train(training)

    total_loss = 0.0
    total_correct = 0
    total_samples = 0

    for ref, test, labels in loader:
        ref = ref.to(device)
        test = test.to(device)
        labels = labels.to(device)

        if training:
            optimizer.zero_grad(set_to_none=True)

        logits, _, _ = model(ref, test)
        loss = criterion(logits, labels)

        if training:
            loss.backward()
            optimizer.step()

        probabilities = torch.sigmoid(logits)
        predictions = (probabilities >= 0.5).float()

        total_loss += float(loss.item()) * ref.size(0)
        total_correct += int((predictions == labels).sum().item())
        total_samples += int(ref.size(0))

    return {
        "loss": total_loss / max(total_samples, 1),
        "accuracy": total_correct / max(total_samples, 1),
        "samples": float(total_samples),
    }


@torch.no_grad()
def evaluate(
    model: TubePairSiamese,
    loader: DataLoader,
    device: str,
    criterion: nn.Module,
) -> dict[str, Any]:
    model.eval()

    total_loss = 0.0
    total_samples = 0
    probabilities: list[float] = []
    labels_list: list[int] = []

    for ref, test, labels in loader:
        ref = ref.to(device)
        test = test.to(device)
        labels = labels.to(device)

        logits, _, _ = model(ref, test)
        loss = criterion(logits, labels)
        probs = torch.sigmoid(logits)

        total_loss += float(loss.item()) * ref.size(0)
        total_samples += int(ref.size(0))
        probabilities.extend(float(value) for value in probs.cpu().tolist())
        labels_list.extend(int(value) for value in labels.cpu().tolist())

    threshold, best_f1 = find_best_threshold(probabilities, labels_list)
    predictions = [1 if prob >= threshold else 0 for prob in probabilities]
    correct = sum(1 for pred, label in zip(predictions, labels_list) if pred == label)
    tp = sum(1 for pred, label in zip(predictions, labels_list) if pred == 1 and label == 1)
    fp = sum(1 for pred, label in zip(predictions, labels_list) if pred == 1 and label == 0)
    fn = sum(1 for pred, label in zip(predictions, labels_list) if pred == 0 and label == 1)
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0

    return {
        "loss": total_loss / max(total_samples, 1),
        "accuracy": correct / max(total_samples, 1),
        "threshold": threshold,
        "f1": best_f1,
        "precision": precision,
        "recall": recall,
        "samples": total_samples,
    }


def main() -> None:
    args = parse_args()
    set_seed(args.seed)
    device = get_device()

    rows = read_rows(args.metadata)
    train_rows, val_rows = split_rows(rows)

    train_dataset = SiamesePairsDataset(train_rows, args.data_root, augment=True)
    val_dataset = SiamesePairsDataset(val_rows, args.data_root, augment=False)

    train_sampler = build_weighted_sampler(train_rows, args.seed) if args.balanced_sampler else None

    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=train_sampler is None,
        sampler=train_sampler,
        num_workers=args.num_workers,
        pin_memory=device == "cuda",
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=device == "cuda",
    )

    positives = sum(int(row["label"]) for row in train_rows)
    negatives = max(len(train_rows) - positives, 1)
    pos_weight = torch.tensor([negatives / max(positives, 1)], device=device, dtype=torch.float32)

    model = TubePairSiamese(embedding_dim=args.embedding_dim).to(device)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    best_score = -math.inf
    best_checkpoint: dict[str, Any] | None = None
    history: list[dict[str, Any]] = []

    print("=" * 60)
    print("  ENTRAINEMENT SIAMESE tube_ref / tube_test")
    print("=" * 60)
    print(f"Device        : {device}")
    print(f"Train samples : {len(train_rows)}")
    print(f"Val samples   : {len(val_rows)}")
    print(f"Train normal  : {negatives}")
    print(f"Train anomaly : {positives}")
    print(f"Sampler       : {'balanced' if args.balanced_sampler else 'random'}")
    print(f"Pos weight    : {float(pos_weight.item()):.4f}")

    for epoch in range(1, args.epochs + 1):
        train_metrics = run_epoch(model, train_loader, device, criterion, optimizer=optimizer)
        val_metrics = evaluate(model, val_loader, device, criterion)
        history.append({"epoch": epoch, "train": train_metrics, "val": val_metrics})

        score = float(val_metrics["f1"])
        if score > best_score:
            best_score = score
            warning_threshold = max(0.2, float(val_metrics["threshold"]) - 0.1)
            anomaly_threshold = float(val_metrics["threshold"])
            best_checkpoint = {
                "model_state": model.state_dict(),
                "config": asdict(
                    SiameseConfig(
                        input_size=args.input_size,
                        embedding_dim=args.embedding_dim,
                        warning_threshold=warning_threshold,
                        anomaly_threshold=anomaly_threshold,
                    )
                ),
                "metrics": val_metrics,
                "history": history,
            }

        print(
            f"Epoch {epoch:02d}/{args.epochs} | "
            f"train_loss={train_metrics['loss']:.4f} train_acc={train_metrics['accuracy']:.4f} | "
            f"val_loss={val_metrics['loss']:.4f} val_acc={val_metrics['accuracy']:.4f} "
            f"val_f1={val_metrics['f1']:.4f} thr={val_metrics['threshold']:.3f}"
        )

    if best_checkpoint is None:
        raise RuntimeError("Training finished without a valid checkpoint")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    torch.save(best_checkpoint, args.output)

    metrics_path = args.output.with_suffix(".metrics.json")
    with metrics_path.open("w", encoding="utf-8") as handle:
        json.dump(
            {
                "best_metrics": best_checkpoint["metrics"],
                "config": best_checkpoint["config"],
                "epochs": args.epochs,
            },
            handle,
            indent=2,
        )

    print("-" * 60)
    print(f"Best checkpoint : {args.output}")
    print(f"Metrics         : {metrics_path}")
    print(f"Best threshold  : {best_checkpoint['metrics']['threshold']:.3f}")


if __name__ == "__main__":
    main()
